name: ExploreHub Frontend Deployment

on:
  push:
  workflow_dispatch:
    branches:
      - main  # Set this to your default branch

jobs:
  build_and_deploy:
    environment: production environment
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set this to the node version you use

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: CI=false npm run build

      - name: Copy Build to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./build/*"
          target: "/var/www/explorehub.lol/html"


